name: Build and test

on:
  push:
    branches: 
      - master
      - feature/setup-ci

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
        
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
        
    - name: Restore NuGet packages
      shell: cmd
      run: nuget restore SimpleContainer.sln
      
    - name: Build
      shell: cmd
      run: dotnet build SimpleContainer.sln
      
    - name: Test
      shell: cmd
      run: packages/nunit.consolerunner/3.10.0/tools/nunit3-console.exe bin/Debug/SimpleContainer.Tests.dll